### ISSUE TITLE
crack working?

### ISSUE THREAD

**Issue by cookins** [BangBuster/smartcopilot-crack#1]
hows exactly crack working? i see demo expired warning. also for what version crack is?
UPD: its seems for version 3.1.2, but its not seems working - there still demo warning.
i got cracked 3.0.3 version.... if author need to check on it...

**Comment by EilayDev** [comment]
The warning still shows, but the demo never expires. You can continue playing indefinitely.

**Comment by cookins** [comment]
> The warning still shows, but the demo never expires. You can continue playing indefinitely.

Yeah, but last version 3.3.0 and that one overwrite with older one? After it applied, it showed 3.1.2. 
can be updated?

**Comment by EilayDev** [comment]
Please try the updated crack (12457605ecb5288e3f438abe6e7812c9fd156a6e) and contact me if it works.
